add tests for icap server

diff --git a/.github/workflows/icap-server.yaml b/.github/workflows/icap-server.yaml
--- a/.github/workflows/icap-server.yaml
+++ b/.github/workflows/icap-server.yaml
@@ -105,3 +105,52 @@ jobs:
           if [[ ! -z "$instance_id" ]]; then
             echo "$instance_id" | while IFS= read -r line ; do aws ec2 terminate-instances --instance-ids $line || true; done
           fi
+
+      - name: Checkout submodules
+        uses: actions/checkout@v2
+        with:
+          repository: k8-proxy/vmware-scripts
+          path: vmware-scripts
+
+      - name: Run tests on the VM
+        id: test
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
+        run: |
+          instance_id="${{ steps.deploy.outputs.instance_id }}"
+          instance_ip="${{ steps.deploy.outputs.instance_ip }}"
+          ami_id="${{ steps.deploy.outputs.ami_id }}"
+          cd vmware-scripts/HealthCheck
+          sed -i "s/54.77.168.168/$instance_ip/g" config.yml
+          sudo apt-get -y install c-icap
+          chmod +x ./pyCheck.py
+          ./pyCheck.py
+          test_result=$?
+          if [[ $test_result -ne 0 ]];then
+            echo ::set-output name=test_result::$test_result
+          else
+            echo "Tests are successfully on the new instance, terminating old instance."
+            aws ec2 create-tags --resources $ami_id --tags Key=Test_Result,Value=Success
+            instance_id="${{ steps.get_id.outputs.instance_id }}"
+            if [[ ! -z "$instance_id" ]]; then
+              echo "$instance_id" | while IFS= read -r line ; do aws ec2 terminate-instances --instance-ids $line || true; done
+            fi
+          fi
+
+      - name: Delete instance if tests fail
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
+        run: |
+          test_result="${{ steps.test.outputs.test_result }}"
+          if [[ $test_result -ne "0" ]];then
+            echo "Failed integration tests, terminating the newly deployed VM"
+            instance_id="${{ steps.deploy.outputs.instance_id }}"
+            ami_id="${{ steps.deploy.outputs.ami_id }}"
+            aws ec2 terminate-instances --instance-ids $instance_id
+            aws ec2 create-tags --resources $ami_id --tags Key=Test_Result,Value=Failed
+          fi
+          exit $test_result
