add tests for proxy-rebuild

diff --git a/.github/workflows/proxy-rebuild.yaml b/.github/workflows/proxy-rebuild.yaml
--- a/.github/workflows/proxy-rebuild.yaml
+++ b/.github/workflows/proxy-rebuild.yaml
@@ -12,6 +12,10 @@ on:
         description: "IP address of ICAP server to be used in proxy server"
         default: "91.211.153.139"
         required: true
+      extra_regions:
+        description: Extra regions where AMI should be published. Pass multiple regions with comma separated.
+        default: eu-west-1
+        required: false
   push:
     branches: [ main ]
     paths-ignore:
@@ -59,7 +63,7 @@ jobs:
       run: |
         cd vmware-scripts/packer
         cp -r target/proxy-rebuild/* setup/
-        packer build -color=false -on-error=cleanup -var github_sha=${{ github.sha }} -var vm_name=proxy-rebuild -var icap_server_ip=${{ github.event.inputs.icap_server_ip }} -var region=${{ env.AWS_DEFAULT_REGION }} -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -var aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws-ami.json
+        packer build -color=false -on-error=cleanup -var github_sha=${{ github.sha }} -var vm_name=proxy-rebuild -var icap_server_ip=${{ github.event.inputs.icap_server_ip }} -var region=${{ env.AWS_DEFAULT_REGION }} -var extra_regions=${{ github.event.inputs.extra_regions }} -var aws_access_key=${{ secrets.AWS_ACCESS_KEY }} -var aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws-ami.json
 
   deploy-ami:
     runs-on: ubuntu-latest
@@ -101,3 +105,44 @@ jobs:
           echo ::set-output name=instance_ip::$instance_ip
           echo ::set-output name=instance_id::$instance_id
           echo ::set-output name=ami_id::$ami_id
+
+      - name: Run tests on the VM
+        id: test
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
+        run: |
+          instance_id="${{ steps.deploy.outputs.instance_id }}"
+          instance_ip="${{ steps.deploy.outputs.instance_ip }}"
+          ami_id="${{ steps.deploy.outputs.ami_id }}"
+          curl -kv https://glasswallsolutions.com/wp-content/uploads/2020/01/Glasswall-d-FIRST-Technology.pdf --resolve "glasswallsolutions.com:443:$instance_ip" --output Glasswall-d-FIRST-Technology.pdf
+          cat Glasswall-d-FIRST-Technology.pdf | grep "Glasswall Processed"
+          test_result=$?
+          if [[ $test_result -ne 0 ]];then
+            echo "Proxy test failed"
+            echo ::set-output name=test_result::$test_result
+          else
+            echo "Tests are successfully on the new instance, terminating old instance."
+            aws ec2 create-tags --resources $ami_id --tags Key=Test_Result,Value=Success
+            instance_id="${{ steps.get_id.outputs.instance_id }}"
+            if [[ ! -z "$instance_id" ]]; then
+              echo "$instance_id" | while IFS= read -r line ; do aws ec2 terminate-instances --instance-ids $line || true; done
+            fi
+          fi
+      - name: Delete instance if tests fail
+        if: ${{ failure() }}
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
+        run: |
+          test_result="${{ steps.test.outputs.test_result }}"
+          if [[ $test_result -ne "0" ]];then
+            echo "Failed integration tests, terminating the newly deployed VM"
+            instance_id="${{ steps.deploy.outputs.instance_id }}"
+            ami_id="${{ steps.deploy.outputs.ami_id }}"
+            aws ec2 terminate-instances --instance-ids $instance_id
+            aws ec2 create-tags --resources $ami_id --tags Key=Test_Result,Value=Failed
+          fi
+          exit $test_result
